<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    "Realty" => "Недвижимость",
    "Districts" => "Кварталы",
    "Districts list" => "Список кварталов",
    "Create district" => "Добавить новый",
    "ReadyTimes" => "Периоды сдачи",
    "ReadyTimes list" => "Список периодов сдачи",
    "Create readyTime" => "Добавить новый",
    "Buildings" => "Дома",
    "Buildings list" => "Список домов",
    "Create building" => "Добавить новый",
    "Builders" => "Застройщики",
    "Builders list" => "Список застройщиков",
    "Create builder" => "Добавить нового",
    "Common" => "Информация",
    "Apartments" => "Квартиры",
    "Images" => "Изображения",

];